"""Focused unit coverage for visual-regression masking."""

from types import SimpleNamespace
from unittest.mock import Mock

from PIL import Image

from tools.rom_tests.emulator import Emulator, screen_difference


def test_ignored_region_masks_only_that_region() -> None:
    reference = Image.new("RGB", (160, 144), "white")
    actual = reference.copy()
    actual.paste("black", (32, 88, 48, 104))
    actual.putpixel((120, 120), (0, 0, 0))

    difference = screen_difference(
        actual,
        reference,
        ignored_regions=((24, 80, 56, 112),),
    )

    assert difference.getpixel((32, 88)) == (0, 0, 0)
    assert difference.getpixel((120, 120)) != (0, 0, 0)
    assert difference.getbbox() == (120, 120, 121, 121)


def test_full_frame_is_compared_without_ignored_regions() -> None:
    reference = Image.new("RGB", (160, 144), "white")
    actual = reference.copy()
    actual.putpixel((80, 120), (0, 0, 0))

    difference = screen_difference(actual, reference)

    assert difference.getbbox() == (80, 120, 81, 121)


def test_symbol_parser_ignores_exported_numeric_constants() -> None:
    lines = (
        "; File generated by rgblink",
        "01 EXPORTED_CONSTANT",
        "00:c000 wExampleValue",
        "0f:4567 ExampleRoutine",
    )

    assert Emulator._parse_symbols(lines) == {
        "wExampleValue": 0xC000,
        "ExampleRoutine": 0x4567,
    }
    assert Emulator._parse_symbol_banks(lines) == {
        "wExampleValue": 0x00,
        "ExampleRoutine": 0x0F,
    }


def test_instruction_replacement_sets_register_and_resumes_after_instruction() -> None:
    emulator = Emulator.__new__(Emulator)
    emulator.symbols = {"Routine.roll": 0x4567}
    emulator.symbol_banks = {"Routine.roll": 0x0F}
    emulator.pyboy = Mock()
    emulator.pyboy.register_file = SimpleNamespace(A=0xFF, PC=0x4567)

    with emulator.replace_instruction_with_register(
        "Routine.roll",
        "A",
        0,
        instruction_bytes=3,
    ):
        callback, context = emulator.pyboy.hook_register.call_args.args[2:]
        callback(context)
        assert emulator.pyboy.register_file.A == 0
        assert emulator.pyboy.register_file.PC == 0x456A
        emulator.pyboy.hook_deregister.assert_not_called()

    emulator.pyboy.hook_register.assert_called_once()
    emulator.pyboy.hook_deregister.assert_called_once_with(0x0F, 0x4567)
